### ISSUE TITLE
query.hash() is not function

### ISSUE THREAD

**Issue by andreyluiz** [tonyhb/tectonic#78]
Here I am again. :P

I'm getting this error while loading my page:

```
TypeError: query.hash is not a function
   at Cache.getQueryStatus (/home/andrey/Projects/Datarisk/app-frontend/node_modules/tectonic/transpiled/cache/index.js:409:49)
   at /home/andrey/Projects/Datarisk/app-frontend/node_modules/tectonic/transpiled/manager/index.js:165:28
   at Array.forEach (native)
   at Manager.props (/home/andrey/Projects/Datarisk/app-frontend/node_modules/tectonic/transpiled/manager/index.js:162:28)
   at PropInspector.computeDependencies (/home/andrey/Projects/Datarisk/app-frontend/node_modules/tectonic/transpiled/decorator/propInspector.js:80:37)
   at new TectonicComponent (/home/andrey/Projects/Datarisk/app-frontend/node_modules/tectonic/transpiled/decorator/index.js:102:43)
   at /home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:295:18
   at measureLifeCyclePerf (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
   at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:294:16)
   at ReactCompositeComponentWrapper._constructComponent (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:280:21)
   at ReactCompositeComponentWrapper.mountComponent (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:188:21)
   at Object.mountComponent (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactReconciler.js:46:35)
   at ReactCompositeComponentWrapper.performInitialMount (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
   at ReactCompositeComponentWrapper.mountComponent (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
   at Object.mountComponent (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactReconciler.js:46:35)
   at ReactCompositeComponentWrapper.performInitialMount (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
```

Did I miss something?

**Comment by tonyhb** [comment]
What are you passing in to the load decorator?

IE.

@load(...)

**Comment by andreyluiz** [comment]
Wow, I looked in your code and felt embarrassed.

Do I need to use it as a decorator?

```javascript
export default load(() => ({
  users: User.list(),
}))(AdminUserListPage);
```

**Comment by tonyhb** [comment]
You'll wanna use something like this:

@load(() => ({
  users: User.getList()
}))

Notice it's getList - this tells load that you want to get a list. The
`list` function is used when specifying sources :)

**Comment by andreyluiz** [comment]
Ah, okay. I though I could use something like the `connect` function from redux.

**Comment by andreyluiz** [comment]
I still have a problem:

Warning: Failed propType: Invalid prop `state` of type `Object` supplied to `TectonicComponent`, expected instance of `Map`.

I'm really struggling to get this running. :|

**Comment by andreyluiz** [comment]
Do you have any idea?

**Comment by tonyhb** [comment]
Got caught up in a few meetings and with some other issues for work.  Gonna hop back on this very soon!

**Comment by andreyluiz** [comment]
Thank you. I'm still trying to find out what's wrong.

**Comment by tonyhb** [comment]
Any updates on this?

**Comment by andreyluiz** [comment]
I ended up doing it by hand. Thank you.
